### PR TITLE
Setup delegateCommandHandler to set KLS classpath entry

### PR DESCRIPTION
**Pull request by daplf**
Fixes https://github.com/fwcd/vscode-java-kotlin/issues/1

This changes the approach taken for interoperability. I removed the project importers and instead we now have a [delegateCommandHandler](https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/plugin.xml#L4) that updates the classpath.

The whole thing works like this:
- KLS starts up
- KLS advertises the output path to the language client (e.g., vscode)
- The language client then forwards this output path to the JDT LS extension using the `delegateCommandHandler`

This PR also introduces the changes need to make this work with the vscode extensions (see also: https://github.com/fwcd/vscode-kotlin/pull/89)

PS: In order to test this, you need the changes from the 3 PRs. For the VSCode side, I'm not sure if you can debug two extensions at once, but you can always package one of them and install it from a vsix (and debug the other one).

### CODE REVIEW

**Comment by daplf** [comment]
@fwcd Thanks for reviewing and merging the client and server PRs. The only thing left now for Java + Kotlin interoperability is this PR. Do you mind taking a look at it? I have rights to merge this as is, but I would prefer if you looked at it as well. Once it's merged, we can publish `vscode-java-kotlin` so people can start trying it out.

**Comment by fwcd** [comment]
I am not very familiar with the JDT.LS APIs yet so I'd have to take some more time to look at this (and the entire extension) in detail, but from a quick glance it definitely looks good to me!

**Comment by fwcd** [comment]
So definitely feel free to merge.

**Comment by daplf** [comment]
Alright, merging it then. Let me know when you've had a chance to look at it, so we can publish it

**Comment by daplf** [comment]
Hey @fwcd 

It's been over a year since I built this companion extension. Perhaps I should just release this myself (if that's okay with you)? There's still many people requesting this every now and then (and having it in the vscode marketplace would be so much easier for them than having to build this themselves)

**Comment by fwcd** [comment]
Hi, sorry for the inactivity on this repo, unfortunately I don't really have the time to actively maintain this project.

> Perhaps I should just release this myself

Sure, feel free to do so! Given that you wrote the extension pretty much yourself, we could also transfer the repo to your account if you'd like. (I'm fine either way, we can leave it here too)

**Comment by daplf** [comment]
> Hi, sorry for the inactivity on this repo, unfortunately I don't really have the time to actively maintain this project.

No worries!

> Sure, feel free to do so! Given that you wrote the extension pretty much yourself, we could also transfer the repo to your account if you'd like. (I'm fine either way, we can leave it here too)

I wrote it myself but it was based on some of your ideas 😄 But I think it makes sense to transfer it to my account, since I'll be the one maintaining it. Can you set that up?

**Comment by fwcd** [comment]
I've sent out a transfer request

**Pull request merged**
